name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Tests Automáticos
      id: tests-automaticos
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Tests Automáticos
        setup-command: ''
        command: bash ./autotest.sh
        timeout: 3
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TESTS-AUTOMATICOS_RESULTS: "${{steps.tests-automaticos.outputs.result}}"
      with:
        runners: tests-automaticos
